### ISSUE TITLE
建议说明更加小白一些

### ISSUE THREAD

**Issue by banjuer** [waterovo/trilium-jsmind#1]
感谢，这个插件非常需要。不过有个建议，可以出个更详细的说明吗？安装第3项没看明白，另外也希望给个如何使用的说明。尝试了一下不太会用

**Comment by waterovo** [comment]
> 感谢，这个插件非常需要。不过有个建议，可以出个更详细的说明吗？安装第3项没看明白，另外也希望给个如何使用的说明。尝试了一下不太会用

好的，后续更新会有更详细的说明，可以先参考以下说明试用。
目前版本还存在bug，期待你的反馈。
1.安装第3项
![image](https://github.com/waterovo/Trilium-jsmind/assets/61768530/8c7fa89a-42cd-42fa-85f1-89d8c9078379)
2.如何使用
jsmind笔记实际上就是特定格式的json笔记；
安装第3项的jmNote关系指向的笔记就是要编辑的jsmind笔记，按照安装第3项的方法更改jmNote关系指向的笔记就能切换要编辑的思维导图；
安装第4项的插件可以在右笔记上角添加一个快捷选项，快速打开要编辑的jsmind笔记。
![image](https://github.com/waterovo/Trilium-jsmind/assets/61768530/413ed7de-1e3c-49c7-a9ac-caffdc83477e)
3.sample笔记被定义为无法更改的笔记，请从左上角菜单新建mindmap
![image](https://github.com/waterovo/Trilium-jsmind/assets/61768530/5eac1944-cf98-46b2-aed5-2e6f1a0f4771)

**Comment by banjuer** [comment]
感谢，知道怎么用了，这样创建的新笔记被引用不能被渲染吧，只能是json的形式预览

**Comment by banjuer** [comment]
另外发现一个问题，新建的文件名字修改后再次打开好像会被重置。之所以需要修改名字，是想让笔记名字更具有可辨别性，方便引用

**Comment by waterovo** [comment]
> 另外发现一个问题，新建的文件名字修改后再次打开好像会被重置。之所以需要修改名字，是想让笔记名字更具有可辨别性，方便引用

可以在菜单的edit metadata修改，后续更新会修改为以笔记标题为准。
1.1版本将更改为显示在笔记右侧
![image](https://github.com/waterovo/Trilium-jsmind/assets/61768530/7b172c64-7731-434a-99cd-4f04ebd30529)

关于引用问题，目前已有思路，不过暂时不会开发这个功能。

**Comment by waterovo** [comment]
已完成更新
