### ISSUE TITLE
可以提俩建议吗

### ISSUE THREAD

**Issue by MASK-LI** [waterovo/trilium-jsmind#4]
可以考虑直接使用渲染的不额外生成吗？这样节点可以直接加上内连接笔记功能诶

**Comment by waterovo** [comment]
不太理解你表述的内容，可以详细描述一下吗

**Comment by MASK-LI** [comment]
![image](https://github.com/waterovo/trilium-jsmind/assets/68579782/0bbcf9c1-7612-467e-8802-83ea400af310)
![image](https://github.com/waterovo/trilium-jsmind/assets/68579782/4596c6e7-6f34-44be-8039-72c7ceebd28f)
这样可以随时修改/也可以跳转到其它笔记

**Comment by MASK-LI** [comment]
大佬  不用看这个了 我用了 新的了

**Comment by MASK-LI** [comment]
> 不太理解你表述的内容，可以详细描述一下吗

已经发到新的那个了
